version: '2'

services:
  builder:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: end2end
    ports:
          - "8000:8000"
    volumes:
      - ..:/app:Z
    command: bash
    tty: true
